package com.ibgi.bean;

import javax.persistence.*;

@Table(name = "`birthdayinfo`")
public class Birthdayinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthdayinfo.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthdayinfo.phone
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthdayinfo.birthday
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthdayinfo.account
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthdayinfo.username
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthdayinfo.legalperson
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String legalperson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthdayinfo.id
     *
     * @return the value of birthdayinfo.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthdayinfo.id
     *
     * @param id the value for birthdayinfo.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthdayinfo.phone
     *
     * @return the value of birthdayinfo.phone
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthdayinfo.phone
     *
     * @param phone the value for birthdayinfo.phone
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthdayinfo.birthday
     *
     * @return the value of birthdayinfo.birthday
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthdayinfo.birthday
     *
     * @param birthday the value for birthdayinfo.birthday
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthdayinfo.account
     *
     * @return the value of birthdayinfo.account
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthdayinfo.account
     *
     * @param account the value for birthdayinfo.account
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthdayinfo.username
     *
     * @return the value of birthdayinfo.username
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthdayinfo.username
     *
     * @param username the value for birthdayinfo.username
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthdayinfo.legalperson
     *
     * @return the value of birthdayinfo.legalperson
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getLegalperson() {
        return legalperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthdayinfo.legalperson
     *
     * @param legalperson the value for birthdayinfo.legalperson
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setLegalperson(String legalperson) {
        this.legalperson = legalperson == null ? null : legalperson.trim();
    }
}