package com.ibgi.bean;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`giftcount`")
public class Giftcount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftcount.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftcount.giftId
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer giftid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftcount.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftcount.count
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftcount.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftcount.modifyTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftcount.id
     *
     * @return the value of giftcount.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftcount.id
     *
     * @param id the value for giftcount.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftcount.giftId
     *
     * @return the value of giftcount.giftId
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getGiftid() {
        return giftid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftcount.giftId
     *
     * @param giftid the value for giftcount.giftId
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setGiftid(Integer giftid) {
        this.giftid = giftid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftcount.location
     *
     * @return the value of giftcount.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftcount.location
     *
     * @param location the value for giftcount.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftcount.count
     *
     * @return the value of giftcount.count
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftcount.count
     *
     * @param count the value for giftcount.count
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftcount.createTime
     *
     * @return the value of giftcount.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftcount.createTime
     *
     * @param createtime the value for giftcount.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftcount.modifyTime
     *
     * @return the value of giftcount.modifyTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftcount.modifyTime
     *
     * @param modifytime the value for giftcount.modifyTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}