package com.ibgi.bean;

import javax.persistence.*;

@Table(name = "`giftlocation`")
public class Giftlocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftlocation.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftlocation.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column giftlocation.comment
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftlocation.id
     *
     * @return the value of giftlocation.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftlocation.id
     *
     * @param id the value for giftlocation.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftlocation.name
     *
     * @return the value of giftlocation.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftlocation.name
     *
     * @param name the value for giftlocation.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column giftlocation.comment
     *
     * @return the value of giftlocation.comment
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column giftlocation.comment
     *
     * @param comment the value for giftlocation.comment
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}