package com.ibgi.bean;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`gift`")
public class Gift {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.status
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.count
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.modifyTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.comment
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.picName
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String picname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.path
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.weights
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer weights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift.land
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer land;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.id
     *
     * @return the value of gift.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.id
     *
     * @param id the value for gift.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.name
     *
     * @return the value of gift.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.name
     *
     * @param name the value for gift.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.status
     *
     * @return the value of gift.status
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.status
     *
     * @param status the value for gift.status
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.count
     *
     * @return the value of gift.count
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.count
     *
     * @param count the value for gift.count
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.createTime
     *
     * @return the value of gift.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.createTime
     *
     * @param createtime the value for gift.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.modifyTime
     *
     * @return the value of gift.modifyTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.modifyTime
     *
     * @param modifytime the value for gift.modifyTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.comment
     *
     * @return the value of gift.comment
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.comment
     *
     * @param comment the value for gift.comment
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.picName
     *
     * @return the value of gift.picName
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getPicname() {
        return picname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.picName
     *
     * @param picname the value for gift.picName
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setPicname(String picname) {
        this.picname = picname == null ? null : picname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.path
     *
     * @return the value of gift.path
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.path
     *
     * @param path the value for gift.path
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.location
     *
     * @return the value of gift.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.location
     *
     * @param location the value for gift.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.weights
     *
     * @return the value of gift.weights
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getWeights() {
        return weights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.weights
     *
     * @param weights the value for gift.weights
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setWeights(Integer weights) {
        this.weights = weights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.land
     *
     * @return the value of gift.land
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getLand() {
        return land;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.land
     *
     * @param land the value for gift.land
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setLand(Integer land) {
        this.land = land;
    }
}