package com.ibgi.bean;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`handoutmanage`")
public class Handoutmanage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handoutmanage.account
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handoutmanage.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handoutmanage.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handoutmanage.account
     *
     * @return the value of handoutmanage.account
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handoutmanage.account
     *
     * @param account the value for handoutmanage.account
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handoutmanage.location
     *
     * @return the value of handoutmanage.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handoutmanage.location
     *
     * @param location the value for handoutmanage.location
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handoutmanage.createTime
     *
     * @return the value of handoutmanage.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handoutmanage.createTime
     *
     * @param createtime the value for handoutmanage.createTime
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}