package com.ibgi.bean;

import javax.persistence.*;

@Table(name = "`land`")
public class Land {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column land.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column land.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column land.id
     *
     * @return the value of land.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column land.id
     *
     * @param id the value for land.id
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column land.name
     *
     * @return the value of land.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column land.name
     *
     * @param name the value for land.name
     *
     * @mbg.generated Tue Sep 11 15:54:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}